import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { geistMono, inter } from "@fonts";

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.className} ${inter.variable} antialiased`}>{children}</body>
    </html>
  );
}
